name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Fawz-Haaroon
          outputs: |
            assets/widgets/snake-animation.svg

      - name: Commit snake if changed
        run: |
          if git status --porcelain | grep "assets/widgets/snake-animation.svg"; then
            git config user.name "profile-bot"
            git config user.email "profile-bot@users.noreply.github.com"
            git add assets/widgets/snake-animation.svg
            git commit -m "chore: update contribution snake" || true
            git push
          fi
