name: Generate Metrics Dashboard

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/dashboards/github-metrics.svg
          token: "+"
          user: Fawz-Haaroon
          template: classic
          base: header, activity, community, repositories
          config_timezone: UTC
